# GenerateVersion.ps1
param (
    [string]$OutputPath = "TwinkieX\Includes\Version.h"
)

# Try to get the latest git tag, fallback to "unknown" if git fails
$gitVersion = "unknown"
try {
    $gitVersion = git describe --tags --always --dirty 2>$null
    if ($LASTEXITCODE -ne 0) { $gitVersion = "unknown" }
} catch { }

$headerContent = @"
#pragma once
// This file is auto-generated by GenerateVersion.ps1
// Do not edit manually!

#define TWINKIEX_VERSION `"$gitVersion`"
"@

# Only overwrite if the content has changed to avoid unnecessary rebuilds
$write = $true
if (Test-Path $OutputPath) {
    $existingContent = Get-Content $OutputPath -Raw
    if ($existingContent -eq $headerContent) {
        $write = $false
    }
}

if ($write) {
    Set-Content -Path $OutputPath -Value $headerContent
    Write-Host "Updated Version.h to $gitVersion"
}
