name: Build and release

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - config: TMCN
            platform: x64
          - config: ESWC
            platform: x86
          - config: TMO
            platform: x86
          - config: TMSX
            platform: x86
          - config: TM1
            platform: x86
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore file timestamps
      uses: chetan/git-restore-mtime-action@v2

    - name: Cache intermediate files
      uses: actions/cache@v4
      with:
        path: Intermediates
        key: ${{ runner.os }}-msbuild-${{ matrix.config }}-${{ matrix.platform }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-msbuild-${{ matrix.config }}-${{ matrix.platform }}-

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project
      run: |
        msbuild TwinkieX.sln `
          /p:Configuration=${{ matrix.config }} `
          /p:Platform=${{ matrix.platform }} `
          /p:IncludePath="${{ github.workspace }}/TwinkieX/Includes" `
          /m

    - name: Install NSIS
      uses: negrutiu/nsis-install@v2

    - name: Create Installer
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/NSIS/Scripts/Output"
        makensis "${{ github.workspace }}/NSIS/Scripts/Installer${{ matrix.config }}.nsi"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Installer-${{ matrix.config }}-${{ matrix.platform }}
        path: ${{ github.workspace }}/NSIS/Scripts/Output/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: installers
          pattern: Installer-*
          merge-multiple: true
      
      - name: Download release notes
        run: wget https://raw.githubusercontent.com/TwinkieTweaks/TwinkieX/refs/heads/development/ReleaseNotes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: installers/*.exe
          body_path: ReleaseNotes.md
