name: Parallel MSBuild and NSIS

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # Define your unique combinations here
        include:
          - config: TMCN
            platform: x64
          - config: ESWC
            platform: x86
          - config: TMO
            platform: x86
          - config: TMSX
            platform: x86

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project
      # We use the matrix variables to fill in the config and platform
      run: |
        msbuild TwinkieX.sln `
          /p:Configuration=${{ matrix.config }} `
          /p:Platform=${{ matrix.platform }} `
          /p:IncludePath="${{ github.workspace }}/TwinkieX/Includes" `
          /m

    - name: Install NSIS
      uses: negrutiu/nsis-install@v2

    - name: Create Installer
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/NSIS/Scripts/Output"
        makensis "${{ github.workspace }}/NSIS/Scripts/Installer${{ matrix.config }}.nsi"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Installer-${{ matrix.config }}-${{ matrix.platform }}
        path: ${{ github.workspace }}/NSIS/Scripts/Output/
