name: Simple MSBuild

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project
      run: msbuild TwinkieX.sln /p:Configuration=TMCN /p:Platform=x64 /p:IncludePath="D:/a/TwinkieX/TwinkieX/TwinkieX/Includes"